/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controle.MonitorControle;
import dao.MonitorHibernateDao;
import dao.MonitorJDBCDao;
import javax.swing.table.TableModel;
import modelo.Monitor;

/**
 *
 * @author regio
 */
public class Tela extends javax.swing.JFrame {
     private int idSelecionado = -1;
      MonitorControle controleJDBC = new MonitorJDBCDao();
      MonitorControle controleHibernate = new MonitorHibernateDao();
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        jtMonitores.setModel(new MonitoresTabela());
        MonitoresTabela model = (MonitoresTabela) jtMonitores.getModel();
        model.setMonitores(controleJDBC.listar());    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfMarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfPreco = new javax.swing.JTextField();
        jcbNovo = new javax.swing.JCheckBox();
        jbCadastrar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMonitores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Marca:");

        jLabel2.setText("Preco:");

        jcbNovo.setText("Novo");

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jtMonitores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtMonitores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtMonitoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtMonitores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfPreco))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbNovo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbNovo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        
        
        Monitor monitor = new Monitor();
        
        
        monitor.setMarca(jtfMarca.getText());
        monitor.setPreco(Integer.valueOf(jtfPreco.getText()));
        monitor.setNovo(jcbNovo.isSelected());
        
        if(idSelecionado >-1){
            monitor.setId(idSelecionado);
            controleJDBC.atualizar(monitor);
            idSelecionado = -1;
        }
        else{
            controleJDBC.salvar(monitor);
        
        }
        
        
        atualizaJTable();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        if(jtMonitores.getSelectedRow() >=0){
            MonitoresTabela mt = (MonitoresTabela) jtMonitores.getModel();
            Monitor m = mt.getSelectedMonitor(jtMonitores.getSelectedRow());
            //remover do banco aqui
            
            //
            mt.removeMonitor(jtMonitores.getSelectedRow());
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jtMonitoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMonitoresMouseClicked
        if(evt.getClickCount() >1){
            MonitoresTabela mt = (MonitoresTabela) jtMonitores.getModel();
            Monitor m = mt.getSelectedMonitor(jtMonitores.getSelectedRow());
            //fazer um tratamento para o ID posteriormente
            idSelecionado = m.getId();            
            jtfMarca.setText(m.getMarca());
            jtfPreco.setText(String.valueOf(m.getPreco()));
            jcbNovo.setSelected(m.getNovo());
        }
    }//GEN-LAST:event_jtMonitoresMouseClicked

    private void atualizaJTable(){
        MonitoresTabela mt = (MonitoresTabela) jtMonitores.getModel();
        mt.setMonitores(controleJDBC.listar());
    }
        
    /**
     * Volta a tela para o estado inicial sem dado nenhum
     */
    private void resetaTela(){
        jtMonitores.setModel(new MonitoresTabela());
        limparTela();
    }
    
    /**
     * Limpa os campos da tela
     */
    private void limparTela(){
        jtfMarca.setText("");
        jtfPreco.setText("");
        jcbNovo.setSelected(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JCheckBox jcbNovo;
    private javax.swing.JTable jtMonitores;
    private javax.swing.JTextField jtfMarca;
    private javax.swing.JTextField jtfPreco;
    // End of variables declaration//GEN-END:variables
}
